import uniqid from "uniqid";
const List = [
  {
    avatar: require("./images/glasses-bl.webp"),
    name: "Gallo Sunglasses",
    id: uniqid(),
    price: 250,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    avatar: require("./images/glasses-blk.webp"),
    name: "Gallo Sunglasses",
    id: uniqid(),
    price: 250,
    description: [
      "Black acetate sunglasses",
      "Non-polarized lenses",
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    avatar: require("./images/glasses-br.webp"),
    name: "Gallo Sunglasses",
    id: uniqid(),
    price: 250,
    description: [
      "Light tortoiseshell acetate sunglasses",
      "Non-polarized lenses",
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    avatar: require("./images/glasses-fire.webp"),
    name: "Gallo Sunglasses",
    id: uniqid(),
    price: 250,
    description: [
      "Tortoiseshell acetate sunglasses",
      "Non-polarized lenses",
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    avatar: require("./images/glasses-wh.webp"),
    name: "Gallo Sunglasses",
    id: uniqid(),
    price: 250,
    description: [
      "Clear acetate sunglasses",
      "Non-polarized lenses",
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    avatar: require("./images/shirt-bl.webp"),
    name: "ALD Uniform Tee",
    id: uniqid(),
    price: 85,
    description: [
      "Navy tee",
      "12oz Jersey fabric",
      "Embroidered logo at center front",
      "Ribbed neck",
      "Featured branded loop label",
      "100% Cotton",
      "Machine wash",
      "Made in Canada",
    ],
  },
  {
    avatar: require("./images/shirt-go.webp"),
    name: "ALD Uniform Tee",
    id: uniqid(),
    price: 85,
    description: [
      "Tan tee",
      "12oz Jersey fabric",
      "Embroidered logo at center front",
      "Ribbed neck",
      "Featured branded loop label",
      "100% Cotton",
      "Machine wash",
      "Made in Canada",
    ],
  },
  {
    avatar: require("./images/shirt-gr.webp"),
    name: "ALD Uniform Tee",
    id: uniqid(),
    price: 85,
    description: [
      "Green tee",
      "12oz Jersey fabric",
      "Embroidered logo at center front",
      "Ribbed neck",
      "Featured branded loop label",
      "100% Cotton",
      "Machine wash",
      "Made in Canada",
    ],
  },
  {
    avatar: require("./images/shirt-gry.webp"),
    name: "ALD Uniform Tee",
    id: uniqid(),
    price: 85,
    description: [
      "Gray tee",
      "12oz Jersey fabric",
      "Embroidered logo at center front",
      "Ribbed neck",
      "Featured branded loop label",
      "100% Cotton",
      "Machine wash",
      "Made in Canada",
    ],
  },
  {
    avatar: require("./images/shirt-wh.webp"),
    name: "ALD Uniform Tee",
    id: uniqid(),
    price: 85,
    description: [
      "White tee",
      "12oz Jersey fabric",
      "Embroidered logo at center front",
      "Ribbed neck",
      "Featured branded loop label",
      "100% Cotton",
      "Machine wash",
      "Made in Canada",
    ],
  },
  {
    avatar: require("./images/shorts-bl.webp"),
    name: "Logo Gym Short",
    id: uniqid(),
    price: 95,
    description: [
      "Blue swim shorts",
      "Embroidered logo at left leg",
      "Mesh lined",
      "Elasticized waistband with flat braided drawstrings",
      "Two on-seam pockets at front",
      "One patch pocket at back",
      "100% Polyester",
      "Machine wash",
      "Made in China",
    ],
  },
  {
    avatar: require("./images/shorts-blk.webp"),
    name: "Logo Gym Short",
    id: uniqid(),
    price: 95,
    description: [
      "Black swim shorts",
      "Embroidered logo at left leg",
      "Mesh lined",
      "Elasticized waistband with flat braided drawstrings",
      "Two on-seam pockets at front",
      "One patch pocket at back",
      "100% Polyester",
      "Machine wash",
      "Made in China",
    ],
  },
  {
    avatar: require("./images/shorts-wh.webp"),
    name: "Logo Gym Short",
    id: uniqid(),
    price: 95,
    description: [
      "White swim shorts",
      "Embroidered logo at left leg",
      "Mesh lined",
      "Elasticized waistband with flat braided drawstrings",
      "Two on-seam pockets at front",
      "One patch pocket at back",
      "100% Polyester",
      "Machine wash",
      "Made in China",
    ],
  },
  {
    avatar: require("./images/shorts-gr.webp"),
    name: "Logo Gym Short",
    id: uniqid(),
    price: 95,
    description: [
      "Green swim shorts",
      "Embroidered logo at left leg",
      "Mesh lined",
      "Elasticized waistband with flat braided drawstrings",
      "Two on-seam pockets at front",
      "One patch pocket at back",
      "100% Polyester",
      "Machine wash",
      "Made in China",
    ],
  },
  {
    avatar: require("./images/shorts-ye.webp"),
    name: "Logo Gym Short",
    id: uniqid(),
    description: [
      "Yellow Gym shorts",
      "Embroidered logo at left leg",
      "Mesh lined",
      "Elasticized waistband with flat braided drawstrings",
      "Two on-seam pockets at front",
      "One patch pocket at back",
      "100% Polyester",
      "Machine wash",
      "Made in China",
    ],
    price: 95,
  },
  {
    avatar: require("./images/shirt-brown.jpg"),
    name: "RROUND Reworked TCD",
    id: uniqid(),
    price: 49,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    avatar: require("./images/shirt.jpg"),
    name: "RROUND Logo",
    id: uniqid(),
    price: 49,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    avatar: require("./images/shorts-rr1.jpg"),
    name: "RROUND Logo Shorts",
    id: uniqid(),
    price: 65,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    avatar: require("./images/shorts-rr.jpg"),
    name: "RROUND Logo Shorts",
    id: uniqid(),
    price: 65,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    avatar: require("./images/shirts-gray.jpg"),
    name: "RROUND Reworked TCD",
    id: uniqid(),
    price: 49,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    avatar: require("./images/hoodie.jpg"),
    name: "RROUND Logo Sweater",
    id: uniqid(),
    price: 250,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    avatar: require("./images/shirt-logo.jpg"),
    name: "RROUND Logo",
    id: uniqid(),
    price: 49,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
];

export default List;
